---

name: Lint Shell
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  differential-shellcheck:
    name: Differential ShellCheck
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: ShellCheck
        name: Differential ShellCheck
        uses: redhat-plumbers-in-action/differential-shellcheck@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - if: ${{ always() }}
        name: Upload artifact with ShellCheck defects in SARIF format
        uses: actions/upload-artifact@v3
        with:
          name: Differential ShellCheck SARIF
          path: ${{ steps.ShellCheck.outputs.sarif }}

  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - run: cargo install shellcheck-sarif sarif-fmt

      - run: shellcheck --format=json innocent-script.sh | shellcheck-sarif | tee
          results.sarif | sarif-fmt

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          category: sarif-rs
          sarif_file: fix-defects.sarif
          token: ${{ secrets.GITHUB_TOKEN }}

...
